name: Build Images

on:
  push:
    branches: [ main ]
    tags:
        - 'v*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build&Push Cluster Service Manager
      uses: docker/build-push-action@v2
      with:
        context: cluster-service-manager/service-manager/
        file: ./Dockerfile
        push: true
        tags: edgeio/edgeionet/cluster-service-manager:experimental-0.01-$(date +%s)
    - name: Build&Push Root Service Manager
      uses: docker/build-push-action@v2
      with:
        context: root-service-manager/service-manager/
        file: ./Dockerfile
        push: true
        tags: edgeio/edgeionet/root-service-manager:experimental-0.01-$(date +%s)
