name: Node Net Manager Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: '^1.20'

      - name: Install dependencies
        working-directory: node-net-manager
        run: |
          go get -u

      - name: Run test suite
        working-directory: node-net-manager
        run: |
           go test ./...